version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli --host 0.0.0.0 --port 8545 --accounts 10 --defaultBalanceEther 1000 --mnemonic "saddle point immune salmon swear indoor riot process easily marine charge leave"
    ports:
      - 8545:8545
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 10s
      retries: 5

  adichain:
    build: .
    stdin_open: true  
    tty: true
    depends_on:
      - ganache
    command: >
      sh -c "
        echo 'Waiting for Ganache to be ready...';
        while ! curl -s http://ganache:8545 >/dev/null; do
          sleep 1;
        done;
        echo 'Ganache is ready, starting ADIChain';
        python /progetto/off_chain/main.py
      "
    environment:
      - ETHEREUM_NODE_URL=http://ganache:8545
    ports:
      - 3000:3000
